apiVersion: v1
kind: Service
metadata:
  name: prometheus-node-port
spec:
  type: NodePort
  ports:
  - nodePort: 30000
    port: 9090
    targetPort: 9090
  selector:
    app.kubernetes.io/name: prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-node-port
spec:
  type: NodePort
  ports:
  - nodePort: 30001
    port: 3000
    targetPort: 3000
  selector:
    app.kubernetes.io/name: grafana
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-node-port
spec:
  type: NodePort
  ports:
  - nodePort: 30002
    port: 9093
    targetPort: 9093
  selector:
    app.kubernetes.io/name: alertmanager