apiVersion: v1
kind: Service
metadata:
  name: prometheus-node-port
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - nodePort: 30900
    port: 9090
    targetPort: 9090
  selector:
    prometheus: k8s